#! /usr/bin/env bash
my_ip=$(ip route get 8.8.8.8 | awk -F"src " 'NR==1{split($2,a," ");print a[1]}')
echo docker run -d --rm -it -v $2:/log -p $my_ip:$1:6006 tensorboard
docker run -d --rm -it -v $2:/log -p $my_ip:$1:6006 tensorboard
